acordes_verso('metallica', ['E', 'G', 'F', 'E']).
acordes_verso('metallica', ['E', 'G', 'A', 'F']).
acordes_verso('metallica', ['Em', 'D', 'C', 'G']).
acordes_verso('metallica', ['Am', 'G', 'F', 'E']).
acordes_verso('metallica', ['B', 'G', 'D', 'A']).
acordes_verso('guns_n_roses', ['D', 'C', 'G', 'F']).
acordes_verso('guns_n_roses', ['D', 'C', 'G', 'D']).
acordes_verso('guns_n_roses', ['G', 'C', 'D', 'A']).
acordes_verso('guns_n_roses', ['G', 'C', 'D', 'A']).
acordes_verso('guns_n_roses', ['A', 'G', 'C', 'D']).
acordes_verso('reik', ['C', 'G', 'Am', 'F']).
acordes_verso('reik', ['G', 'D', 'Em', 'C']).
acordes_verso('reik', ['Em', 'C', 'G', 'D']).
acordes_verso('reik', ['G', 'D', 'Em', 'C']).
acordes_verso('reik', ['Am', 'F', 'C', 'G']).
acordes_verso('mana', ['G', 'D', 'Em', 'C']).
acordes_verso('mana', ['Em', 'G', 'D', 'C']).
acordes_verso('mana', ['C', 'G', 'Am', 'F']).
acordes_verso('mana', ['G', 'D', 'Em', 'C']).
acordes_verso('mana', ['Am', 'F', 'C', 'G']).

acordes_precoro('metallica', ['C', 'D', 'E', 'G']).
acordes_precoro('metallica', ['D', 'C', 'G', 'E']).
acordes_precoro('metallica', ['G', 'B', 'Em', 'D']).
acordes_precoro('metallica', ['C', 'G', 'Am', 'E']).
acordes_precoro('metallica', ['A', 'G', 'B', 'E']).
acordes_precoro('guns_n_roses', ['A', 'C', 'D', 'F']).
acordes_precoro('guns_n_roses', ['C', 'G', 'D', 'Em']).
acordes_precoro('guns_n_roses', ['A', 'C', 'G', 'D']).
acordes_precoro('guns_n_roses', ['A', 'C', 'D', 'G']).
acordes_precoro('guns_n_roses', ['D', 'C', 'G', 'A']).
acordes_precoro('reik', ['F', 'G', 'C', 'Am']).
acordes_precoro('reik', ['Em', 'C', 'G', 'D']).
acordes_precoro('reik', ['C', 'D', 'Em', 'G']).
acordes_precoro('reik', ['Em', 'C', 'G', 'D']).
acordes_precoro('reik', ['F', 'G', 'Am', 'C']).
acordes_precoro('mana', ['C', 'D', 'Em', 'G']).
acordes_precoro('mana', ['C', 'D', 'Em', 'G']).
acordes_precoro('mana', ['F', 'G', 'Am', 'C']).
acordes_precoro('mana', ['C', 'D', 'Em', 'G']).
acordes_precoro('mana', ['F', 'G', 'Am', 'C']).

acordes_coro('metallica', ['E', 'G', 'F', 'E']).
acordes_coro('metallica', ['A', 'G', 'F', 'E']).
acordes_coro('metallica', ['C', 'D', 'Em', 'G']).
acordes_coro('metallica', ['E', 'G', 'F', 'Am']).
acordes_coro('metallica', ['D', 'G', 'B', 'A']).
acordes_coro('guns_n_roses', ['D', 'C', 'G', 'F']).
acordes_coro('guns_n_roses', ['C', 'G', 'D', 'Em']).
acordes_coro('guns_n_roses', ['G', 'C', 'D', 'A']).
acordes_coro('guns_n_roses', ['G', 'C', 'D', 'A']).
acordes_coro('guns_n_roses', ['A', 'G', 'C', 'D']).
acordes_coro('reik', ['C', 'G', 'Am', 'F']).
acordes_coro('reik', ['G', 'D', 'Em', 'C']).
acordes_coro('reik', ['Em', 'C', 'G', 'D']).
acordes_coro('reik', ['G', 'D', 'Em', 'C']).
acordes_coro('reik', ['Am', 'F', 'C', 'G']).
acordes_coro('mana', ['G', 'D', 'Em', 'C']).
acordes_coro('mana', ['Em', 'G', 'D', 'C']).
acordes_coro('mana', ['C', 'G', 'Am', 'F']).
acordes_coro('mana', ['G', 'D', 'Em', 'C']).
acordes_coro('mana', ['Am', 'F', 'C', 'G']).

acordes_puente('metallica', ['D', 'E', 'F', 'G']).
acordes_puente('metallica', ['B', 'C', 'D', 'E']).
acordes_puente('metallica', ['C', 'G', 'D', 'Em']).
acordes_puente('metallica', ['D', 'C', 'G', 'E']).
acordes_puente('metallica', ['F', 'G', 'A', 'E']).
acordes_puente('guns_n_roses', ['A', 'G', 'C', 'D']).
acordes_puente('guns_n_roses', ['Em', 'G', 'A', 'D']).
acordes_puente('guns_n_roses', ['A', 'C', 'G', 'D']).
acordes_puente('guns_n_roses', ['A', 'G', 'C', 'D']).
acordes_puente('guns_n_roses', ['C', 'D', 'G', 'A']).
acordes_puente('reik', ['Am', 'F', 'G', 'C']).
acordes_puente('reik', ['C', 'D', 'Em', 'G']).
acordes_puente('reik', ['Am', 'Em', 'C', 'D']).
acordes_puente('reik', ['C', 'D', 'Em', 'G']).
acordes_puente('reik', ['C', 'Am', 'F', 'G']).
acordes_puente('mana', ['Am', 'C', 'G', 'D']).
acordes_puente('mana', ['Am', 'C', 'G', 'D']).
acordes_puente('mana', ['Am', 'F', 'G', 'C']).
acordes_puente('mana', ['Am', 'C', 'G', 'D']).
acordes_puente('mana', ['C', 'Am', 'F', 'G']).